version: '3.7'

services:
  db:
    image: postgres
    restart: always
    environment:
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_USER=postgres 
        - POSTGRES_DB=db
    volumes:
        - mydb:/var/lib/postgresql/data 
    ports:
        - 5432:5432
volumes:
  mydb:
